In [5]:
# matrix operations

import numpy as np

def sum_matrix(left_matrix: np.ndarray, right_matrix: np.ndarray) -> None:
    result = left_matrix + right_matrix
    print(result)  

def substract_matrix(left_matrix: np.ndarray, right_matrix: np.ndarray) -> None:
    result = left_matrix - right_matrix
    print(result)  

def multiply_two_matrices(left_matrix: np.ndarray, right_matrix: np.ndarray) -> np.ndarray:
    result = np.dot(left_matrix, right_matrix)
    print(result)
    return result

def multiply_three_matrices(first_matrix: np.ndarray, second_matrix: np.ndarray, third_matrix: np.ndarray) -> None:
    first_multiplication_result = multiply_two_matrices(first_matrix, second_matrix)
    result = np.dot(first_multiplication_result, third_matrix)
    print(result)  

In [6]:
a = np.array([[1, 2, 4],
              [7, 5, -2],
              [-2, 1, 3]
             ])
b = np.array([[-1, 0, 3],
              [2, -6, 1],
              [-7, 1, 5]
             ])
c = np.array([[-2, 3],
              [4, 0],
              [7, -1]
             ])

print("A+B\n")
sum_matrix(a, b)
print("B-A\n")
substract_matrix(b, a)
print("A*C\n")
multiply_two_matrices(a, c)
print("A*B*C\n")
multiply_three_matrices(a, b, c)

A+B

[[ 0  2  7]
 [ 9 -1 -1]
 [-9  2  8]]
B-A

[[ -2  -2  -1]
 [ -5 -11   3]
 [ -5   0   2]]
A*C

[[34 -1]
 [-8 23]
 [29 -9]]
A*B*C

[[-25  -8  25]
 [ 17 -32  16]
 [-17  -3  10]]
[[ 193 -100]
 [ -50   35]
 [  92  -61]]


In [7]:
a = np.array([[0, 3, 4],
              [-7, 1, -2],
              [2, -1, 3]
             ])
b = np.array([[1, 2, 4],
              [7, 0, -2],
              [-3, -2, 5]
             ])
c = np.array([[-3, 2],
              [0, 4],
              [-1, 7]
             ])

print("A+B\n")
sum_matrix(a, b)
print("B-A\n")
substract_matrix(b, a)
print("A*C\n")
multiply_two_matrices(a, c)
print("A*B*C\n")
multiply_three_matrices(a, b, c)

A+B

[[ 1  5  8]
 [ 0  1 -4]
 [-1 -3  8]]
B-A

[[ 1 -1  0]
 [14 -1  0]
 [-5 -1  2]]
A*C

[[ -4  40]
 [ 23 -24]
 [ -9  21]]
A*B*C

[[  9  -8  14]
 [  6 -10 -40]
 [-14  -2  25]]
[[ -41   84]
 [  22 -308]
 [  17  139]]


In [8]:
a = np.array([[5, 2, 9],
              [7, 0, -2],
              [-2, 1, 6]
             ])
b = np.array([[1, -2, 1],
              [7, 5, -2],
              [-2, 8, 3]
             ])
c = np.array([[-2, 3],
              [4, 5],
              [0, -1]
             ])

print("A+B\n")
sum_matrix(a, b)
print("B-A\n")
substract_matrix(b, a)
print("A*C\n")
multiply_two_matrices(a, c)
print("A*B*C\n")
multiply_three_matrices(a, b, c)

A+B

[[ 6  0 10]
 [14  5 -4]
 [-4  9  9]]
B-A

[[-4 -4 -8]
 [ 0  5  0]
 [ 0  7 -3]]
A*C

[[ -2  16]
 [-14  23]
 [  8  -7]]
A*B*C

[[  1  72  28]
 [ 11 -30   1]
 [ -7  57  14]]
[[ 286  335]
 [-142 -118]
 [ 242  250]]


In [9]:
a = np.array([[1, -2, 8],
              [7, 5, -2],
              [-2, 3, 0]
             ])
b = np.array([[0, 2, 4],
              [1, -3, -2],
              [-2, 1, 3]
             ])
c = np.array([[0, 3],
              [5, -4],
              [7, -1]
             ])

print("A+B\n")
sum_matrix(a, b)
print("B-A\n")
substract_matrix(b, a)
print("A*C\n")
multiply_two_matrices(a, c)
print("A*B*C\n")
multiply_three_matrices(a, b, c)

A+B

[[ 1  0 12]
 [ 8  2 -4]
 [-4  4  3]]
B-A

[[-1  4 -4]
 [-6 -8  0]
 [ 0 -2  3]]
A*C

[[ 46   3]
 [ 11   3]
 [ 15 -18]]
A*B*C

[[-18  16  32]
 [  9  -3  12]
 [  3 -13 -14]]
[[ 304 -150]
 [  69   27]
 [-163   75]]


In [10]:
a = np.array([[9, 2, 4],
              [7, 5, -5],
              [6, -2, 3]
             ])
b = np.array([[8, 2, 4],
              [0, 1, -3],
              [-2, 1, 6]
             ])
c = np.array([[-2, 0],
              [4, 8],
              [1, -1]
             ])

print("A+B\n")
sum_matrix(a, b)
print("B-A\n")
substract_matrix(b, a)
print("A*C\n")
multiply_two_matrices(a, c)
print("A*B*C\n")
multiply_three_matrices(a, b, c)

A+B

[[17  4  8]
 [ 7  6 -8]
 [ 4 -1  9]]
B-A

[[-1  0  0]
 [-7 -4  2]
 [-8  3  3]]
A*C

[[ -6  12]
 [  1  45]
 [-17 -19]]
A*B*C

[[ 64  24  54]
 [ 66  14 -17]
 [ 42  13  48]]
[[ 22 138]
 [-93 129]
 [ 16  56]]


In [72]:
# комбинаторика

import math

# задача 1

# Функция math.perm(n, k) в Python вычисляет количество перестановок без повторений — 
# то есть количество способов выбрать и расположить 𝑘 элементов из 𝑛 различных объектов.
# perm(𝑛,𝑘) = 𝑛! / (𝑛−𝑘)!

task_1_result = math.perm(30, 3)
print(f"Task 1: {task_1_result}")

# задача 2
task_2_result = 2 ** 10
print(f"Task 2: {task_2_result}")

# задача 3
task_3_result = 30 + 50
print(f"Task 3: {task_3_result}")

# задача 5
task_5_result = math.factorial(7)
print(f"Task 5: {task_5_result}")

# задача 6
task_6_result = math.perm(10, 5)
print(f"Task 6: {task_6_result}")

# задача 7

# Функция math.comb(X, Y) в Python вычисляет число сочетаний — 
# то есть количество способов выбрать Y элемента из X, без учёта порядка.
# comb(𝑛,𝑘)= 𝑛! / 𝑘! * (𝑛−𝑘)!

task_7_result = 16 * 15 / 2
task_7_result_alternative = math.comb(16, 2)
print(f"Task 7: {task_7_result}")
print(f"Task 7 alternative: {task_7_result_alternative}")

# задача 8
task_8_result = math.comb(10, 5)
print(f"Task 8: {task_8_result}")

# задача 9
possible_combination_1 = [1, 1, 4]
possible_combination_2 = [1, 2, 3]
possible_combination_3 = [2, 2, 2]
task_9_result = 3 + 6 + 1
print(f"Task 9: {task_9_result}")

# задача 10

# Формула для перестановок с повторениями:
# Количество уникальных перестановок = 𝑛! / 𝑘1! * 𝑘2 * ⋯ * 𝑘𝑟!

possible_combination_1 = [0, 0, 0, 5] # 3 + 1
possible_combination_2 = [0, 0, 1, 4] # 1 + 1 + 2
possible_combination_3 = [0, 1, 1, 3] # 1 + 1 + 2
possible_combination_4 = [0, 0, 2, 3] # 1 + 1 + 2
possible_combination_5 = [1, 1, 1, 2] # 1 + 3
possible_combination_6 = [0, 1, 2, 2] # 1 + 1 + 2
task_10_result = (
    2 * (math.factorial(4) / (math.factorial(1) * math.factorial(3)))
    + 4 * (math.factorial(4) / (math.factorial(1) * math.factorial(1) * math.factorial(2)))
) 
print(f"Task 10: {task_10_result}")

# задача 11
task_11_result = math.factorial(25) / (math.factorial(6) * math.factorial(9) * math.factorial(10))
print(f"[?] Task 11: {task_11_result}")

# задача 12
possible_combination_1 = [4, 4, 4, 5, 5, 6, 6] # 3 + 2 + 2
task_12_result = math.factorial(7) / (math.factorial(3) * math.factorial(2) * math.factorial(2))
print(f"Task 12: {task_12_result}")

Task 1: 24360
Task 2: 1024
Task 3: 80
Task 5: 5040
Task 6: 30240
Task 7: 120.0
Task 7 alternative: 120
Task 8: 252
Task 9: 10
Task 10: 56.0
[?] Task 11: 16360143800.0
Task 12: 210.0


In [69]:
# вероятность 1

# задача 1
task_1_result = (5 / 9) * (4 / 8) * (3 / 7)
print(f"Task 1: {(task_1_result):.2f}")

# задача 2
task_2_result = 1 - (10 * 9 * 8) / (10 ** 3)
print(f"Task 2: {task_2_result}")

# задача 3
total_8_digit_numbers_amount = 10 ** 7 * 9

# all digit combinations according to the task
equal_number_choice_amount = 10
equal_number_position_amount = math.comb(8, 4)
not_equal_numbers_position_amount = 9 * 8 * 7 * 6 #math.perm(9, 4)
all_possible_combinations_amount = equal_number_choice_amount * equal_number_position_amount * not_equal_numbers_position_amount

# combinations, where 0 could be on 1st place and it is an equal number
zero_is_equal_number_not_first_position_amount = math.comb(7, 3) 
other_not_equal_numbers_position_amount = 9 * 8 * 7 * 6 #math.perm(9, 4)
zero_first_all_cases_amount = zero_is_equal_number_not_first_position_amount * other_not_equal_numbers_position_amount

# combinations, where 0 could be on 1st place and it is not an equal number
zero_first_and_not_equal_equal_number_choice_amount = 9
zero_first_and_not_equal_equal_number_position_amount = math.comb(7, 4)
zero_first_and_not_equal_not_equal_numbers_position_amount = 8 * 7 * 6 #math.perm(8, 3)
zero_first_and_not_equal_all_possible_combinations_amount = zero_first_and_not_equal_equal_number_choice_amount * zero_first_and_not_equal_equal_number_position_amount * zero_first_and_not_equal_not_equal_numbers_position_amount

task_3_result = (all_possible_combinations_amount - zero_first_all_cases_amount - zero_first_and_not_equal_all_possible_combinations_amount) / total_8_digit_numbers_amount
print(f"Task 3: {(task_3_result):.2f}")

# задача 4

# 1 - (обратились во все)

all_possible_applications = 5 ** 6
task_4_result = -1
print(f"[ASK] Task 4: {task_4_result}")

Task 1: 0.12
Task 2: 0.28
Task 3: 0.02
[ASK] Task 4: -1


In [67]:
# вероятность 2 (основные формулы)

# задача 1
task_1_result = (math.comb(10, 2) + math.comb(5, 2)) / math.comb(15, 2)
print(f"Task 1: {(task_1_result):.2f}")

# задача 2

only_english = 0.13
only_german = 0.20
only_french = 0.30 
english_and_german = 0.05
english_and_french = 0.07
german_and_french = 0.02 
english_and_german_and_french = 0.03

total_english = 0.28
total_german = 0.3
total_french = 0.24

print(f"Task 2 a: {(total_english + total_german - (english_and_german + english_and_german_and_french)):.2f}")
print(f"Task 2 b: {(only_english + only_german + only_french + english_and_german + english_and_french + german_and_french + english_and_german_and_french):.2f}")
print(f"Task 2 c: {(1 - (only_english + only_german + only_french + english_and_german + english_and_french + german_and_french + english_and_german_and_french)):.2f}")

# задача 3

combination_1 = ['M', 'M']
combination_2 = ['W', 'W']
task_3_result = 1 / 2
print(f"Task 3: {task_3_result}")

Task 1: 0.52
Task 2 a: 0.50
Task 2 b: 0.80
Task 2 c: 0.20
Task 3: 0.5
